In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import seaborn as sns
import itertools

In [2]:
#!wget https://gist.github.com/DiogoRibeiro7/c6590d0cf119e87c39e31c21a9c0f3a8
play_tennis = pd.read_csv("PlayTennis.csv")
play_tennis

Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

# New Section

In [6]:
Outlook=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
Temperature=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
Humidity=['high','high','high','high','normal','normal','normal','high','normal','normal','normal','high','normal','high']
Wind=['False','True','False','False','False','True','True','False','False','False','True','True','False','True']
PlayTennis=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']


In [7]:
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
Outlook_encoded=le.fit_transform(Outlook)
print(Outlook_encoded)
Temperature_encoded=le.fit_transform(Temperature)
print(Temperature_encoded)
Humidity_encoded=le.fit_transform(Humidity)
print(Humidity_encoded)
Wind_encoded=le.fit_transform(Wind)
print(Wind_encoded)
#play_encoded=le.fit_transform(play)
#print(play_encoded)
label=le.fit_transform(PlayTennis)
print(label)


[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[0 1 0 0 0 1 1 0 0 0 1 1 0 1]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [3]:
number = LabelEncoder()
play_tennis['Outlook'] = number.fit_transform(play_tennis['Outlook'])
play_tennis['Temperature'] = number.fit_transform(play_tennis['Temperature'])
play_tennis['Humidity'] = number.fit_transform(play_tennis['Humidity'])
play_tennis['Wind'] = number.fit_transform(play_tennis['Wind'])
play_tennis['PlayTennis'] = number.fit_transform(play_tennis['Play Tennis'])
print("outlook")
print(play_tennis['Outlook'])
print("temp")
print(play_tennis['Temperature'])
print("humid")
print(play_tennis['Humidity'])
print("wind")
print(play_tennis['Wind'])

outlook
0     2
1     2
2     0
3     1
4     1
5     1
6     0
7     2
8     2
9     1
10    2
11    0
12    0
13    1
Name: Outlook, dtype: int64
temp
0     1
1     1
2     1
3     2
4     0
5     0
6     0
7     2
8     0
9     2
10    2
11    2
12    1
13    2
Name: Temperature, dtype: int64
humid
0     0
1     0
2     0
3     0
4     1
5     1
6     1
7     0
8     1
9     1
10    1
11    0
12    1
13    0
Name: Humidity, dtype: int64
wind
0     1
1     0
2     1
3     1
4     1
5     0
6     0
7     1
8     1
9     1
10    0
11    0
12    1
13    0
Name: Wind, dtype: int64


In [8]:
features = ["Outlook", "Temperature", "Humidity", "Wind"]
target = "Play Tennis"
target

'Play Tennis'

In [9]:
features_train, features_test, target_train, target_test = train_test_split(play_tennis[features],
play_tennis[target],
test_size = 0.33,
random_state = 54)

In [10]:
X=play_tennis[features]
y=play_tennis[target]
display(X.shape,y.shape)

(14, 4)

(14,)

In [11]:
#After extracting the data attributes and corresponding labels -split them into train and test data sets from X and y
#for this We have to use scikit-learn's model selection library
#import library for splitting the dataset into train and test
from sklearn.model_selection import train_test_split
#Using the train_test_split to create randomly train and test sets 
#train samples 50 (any number can be given) and test=0.25 means 25% of data is test data
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=50,test_size=0.2)

In [12]:
#classifier using Decision Tree
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [13]:
y_pred=clf.predict(X_test)
y_pred

array(['Yes', 'No', 'Yes'], dtype=object)

In [14]:
from sklearn import metrics
print('Accuracy Score on train Data (using default criterion gini):', metrics.accuracy_score(y_true=y_train, y_pred=clf.predict(X_train)))
print('Accuracy Score on test Data (using default criterion gini):', metrics.accuracy_score(y_true=y_test, y_pred=y_pred))

Accuracy Score on train Data (using default criterion gini): 1.0
Accuracy Score on test Data (using default criterion gini): 0.6666666666666666


In [15]:
clf_entropy = DecisionTreeClassifier(criterion='entropy')
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [16]:
y_pred_entropy= clf_entropy.predict(X_test)
print('Accuracy Score on train Data (using default criterion entropy):', metrics.accuracy_score(y_true=y_train, y_pred=clf.predict(X_train)))
print('Accuracy Score on test Data (using default criterion entropy):', metrics.accuracy_score(y_true=y_test, y_pred=y_pred))

Accuracy Score on train Data (using default criterion entropy): 1.0
Accuracy Score on test Data (using default criterion entropy): 0.6666666666666666


In [17]:
#tune the parameters of the decision tree to increase the accuracy
#use minimum sample split
clf2=DecisionTreeClassifier(criterion='entropy',min_samples_split=50)
clf2.fit(X_train, y_train)
print('Accuracy Score on train Data (using default criterion entropy):', metrics.accuracy_score(y_true=y_train, y_pred=clf2.predict(X_train)))
print('Accuracy Score on test Data (using default criterion entropy):', metrics.accuracy_score(y_true=y_test, y_pred=y_pred))

Accuracy Score on train Data (using default criterion entropy): 0.5454545454545454
Accuracy Score on test Data (using default criterion entropy): 0.6666666666666666


In [ ]:
#https://colab.research.google.com/github/goodboychan/chans_jupyter/blob/master/_notebooks/2020-06-03-01-Decision-tree-for-classification.ipynb#scrollTo=UQNAAih7QtEz